window.esdocSearchIndex = [
  [
    "koa-smart/src/app.js~app",
    "class/src/App.js~App.html",
    "<span>App</span> <span class=\"search-result-import-path\">koa-smart/src/App.js</span>",
    "class"
  ],
  [
    "koa-smart/src/utils/errorapp.js~errorapp",
    "class/src/utils/ErrorApp.js~ErrorApp.html",
    "<span>ErrorApp</span> <span class=\"search-result-import-path\">koa-smart/src/utils/ErrorApp.js</span>",
    "class"
  ],
  [
    "koa-smart/src/routes/route.js~route",
    "class/src/routes/Route.js~Route.html",
    "<span>Route</span> <span class=\"search-result-import-path\">koa-smart/src/routes/Route.js</span>",
    "class"
  ],
  [
    "koa-smart/src/middlewares/handleerror.js~handleerror",
    "function/index.html#static-function-handleError",
    "<span>handleError</span> <span class=\"search-result-import-path\">koa-smart/src/middlewares/handleError.js</span>",
    "function"
  ],
  [
    "src/app.js",
    "file/src/App.js.html",
    "src/App.js",
    "file"
  ],
  [
    "src/app.js~app#addmiddleware",
    "class/src/App.js~App.html#instance-method-addMiddleware",
    "src/App.js~App#addMiddleware",
    "method"
  ],
  [
    "src/app.js~app#addmiddlewares",
    "class/src/App.js~App.html#instance-method-addMiddlewares",
    "src/App.js~App#addMiddlewares",
    "method"
  ],
  [
    "src/app.js~app#constructor",
    "class/src/App.js~App.html#instance-constructor-constructor",
    "src/App.js~App#constructor",
    "method"
  ],
  [
    "src/app.js~app#mountfolder",
    "class/src/App.js~App.html#instance-method-mountFolder",
    "src/App.js~App#mountFolder",
    "method"
  ],
  [
    "src/app.js~app#start",
    "class/src/App.js~App.html#instance-method-start",
    "src/App.js~App#start",
    "method"
  ],
  [
    "src/middlewares/handleerror.js",
    "file/src/middlewares/handleError.js.html",
    "src/middlewares/handleError.js",
    "file"
  ],
  [
    "src/middlewares/handleerror.js~optionerrors",
    "typedef/index.html#static-typedef-OptionErrors",
    "src/middlewares/handleError.js~OptionErrors",
    "typedef"
  ],
  [
    "src/routes/route.js",
    "file/src/routes/Route.js.html",
    "src/routes/Route.js",
    "file"
  ],
  [
    "src/routes/route.js~koa",
    "http://koajs.com/#application",
    "src/routes/Route.js~Koa",
    "external"
  ],
  [
    "src/routes/route.js~koacontext",
    "http://koajs.com/#api",
    "src/routes/Route.js~KoaContext",
    "external"
  ],
  [
    "src/routes/route.js~route#addratelimit",
    "class/src/routes/Route.js~Route.html#instance-method-addRateLimit",
    "src/routes/Route.js~Route#addRateLimit",
    "method"
  ],
  [
    "src/routes/route.js~route#allroutesinstance",
    "class/src/routes/Route.js~Route.html#instance-member-allRoutesInstance",
    "src/routes/Route.js~Route#allRoutesInstance",
    "member"
  ],
  [
    "src/routes/route.js~route#app",
    "class/src/routes/Route.js~Route.html#instance-member-app",
    "src/routes/Route.js~Route#app",
    "member"
  ],
  [
    "src/routes/route.js~route#assert",
    "class/src/routes/Route.js~Route.html#instance-method-assert",
    "src/routes/Route.js~Route#assert",
    "method"
  ],
  [
    "src/routes/route.js~route#beforeroute",
    "class/src/routes/Route.js~Route.html#instance-method-beforeRoute",
    "src/routes/Route.js~Route#beforeRoute",
    "method"
  ],
  [
    "src/routes/route.js~route#body",
    "class/src/routes/Route.js~Route.html#instance-method-body",
    "src/routes/Route.js~Route#body",
    "method"
  ],
  [
    "src/routes/route.js~route#bodyget",
    "class/src/routes/Route.js~Route.html#instance-method-bodyGet",
    "src/routes/Route.js~Route#bodyGet",
    "method"
  ],
  [
    "src/routes/route.js~route#constructor",
    "class/src/routes/Route.js~Route.html#instance-constructor-constructor",
    "src/routes/Route.js~Route#constructor",
    "method"
  ],
  [
    "src/routes/route.js~route#disable",
    "class/src/routes/Route.js~Route.html#instance-member-disable",
    "src/routes/Route.js~Route#disable",
    "member"
  ],
  [
    "src/routes/route.js~route#koarouter",
    "class/src/routes/Route.js~Route.html#instance-member-koaRouter",
    "src/routes/Route.js~Route#koaRouter",
    "member"
  ],
  [
    "src/routes/route.js~route#log",
    "class/src/routes/Route.js~Route.html#instance-method-log",
    "src/routes/Route.js~Route#log",
    "method"
  ],
  [
    "src/routes/route.js~route#middlewares",
    "class/src/routes/Route.js~Route.html#instance-member-middlewares",
    "src/routes/Route.js~Route#middlewares",
    "member"
  ],
  [
    "src/routes/route.js~route#model",
    "class/src/routes/Route.js~Route.html#instance-member-model",
    "src/routes/Route.js~Route#model",
    "member"
  ],
  [
    "src/routes/route.js~route#models",
    "class/src/routes/Route.js~Route.html#instance-member-models",
    "src/routes/Route.js~Route#models",
    "member"
  ],
  [
    "src/routes/route.js~route#mount",
    "class/src/routes/Route.js~Route.html#instance-method-mount",
    "src/routes/Route.js~Route#mount",
    "method"
  ],
  [
    "src/routes/route.js~route#paramsget",
    "class/src/routes/Route.js~Route.html#instance-method-paramsGet",
    "src/routes/Route.js~Route#paramsGet",
    "method"
  ],
  [
    "src/routes/route.js~route#prefix",
    "class/src/routes/Route.js~Route.html#instance-member-prefix",
    "src/routes/Route.js~Route#prefix",
    "member"
  ],
  [
    "src/routes/route.js~route#send",
    "class/src/routes/Route.js~Route.html#instance-method-send",
    "src/routes/Route.js~Route#send",
    "method"
  ],
  [
    "src/routes/route.js~route#sendbadrequest",
    "class/src/routes/Route.js~Route.html#instance-method-sendBadRequest",
    "src/routes/Route.js~Route#sendBadRequest",
    "method"
  ],
  [
    "src/routes/route.js~route#sendcreated",
    "class/src/routes/Route.js~Route.html#instance-method-sendCreated",
    "src/routes/Route.js~Route#sendCreated",
    "method"
  ],
  [
    "src/routes/route.js~route#sendforbidden",
    "class/src/routes/Route.js~Route.html#instance-method-sendForbidden",
    "src/routes/Route.js~Route#sendForbidden",
    "method"
  ],
  [
    "src/routes/route.js~route#sendinternalservererror",
    "class/src/routes/Route.js~Route.html#instance-method-sendInternalServerError",
    "src/routes/Route.js~Route#sendInternalServerError",
    "method"
  ],
  [
    "src/routes/route.js~route#sendnocontent",
    "class/src/routes/Route.js~Route.html#instance-method-sendNoContent",
    "src/routes/Route.js~Route#sendNoContent",
    "method"
  ],
  [
    "src/routes/route.js~route#sendnotfound",
    "class/src/routes/Route.js~Route.html#instance-method-sendNotFound",
    "src/routes/Route.js~Route#sendNotFound",
    "method"
  ],
  [
    "src/routes/route.js~route#sendok",
    "class/src/routes/Route.js~Route.html#instance-method-sendOk",
    "src/routes/Route.js~Route#sendOk",
    "method"
  ],
  [
    "src/routes/route.js~route#sendunauthorized",
    "class/src/routes/Route.js~Route.html#instance-method-sendUnauthorized",
    "src/routes/Route.js~Route#sendUnauthorized",
    "method"
  ],
  [
    "src/routes/route.js~route#throw",
    "class/src/routes/Route.js~Route.html#instance-method-throw",
    "src/routes/Route.js~Route#throw",
    "method"
  ],
  [
    "src/routes/route.js~route.decorator",
    "typedef/index.html#static-typedef-Decorator",
    "src/routes/Route.js~Route.Decorator",
    "typedef"
  ],
  [
    "src/routes/route.js~route.delete",
    "class/src/routes/Route.js~Route.html#static-member-Delete",
    "src/routes/Route.js~Route.Delete",
    "member"
  ],
  [
    "src/routes/route.js~route.get",
    "class/src/routes/Route.js~Route.html#static-member-Get",
    "src/routes/Route.js~Route.Get",
    "member"
  ],
  [
    "src/routes/route.js~route.parammiddlewarefunction",
    "typedef/index.html#static-typedef-ParamMiddlewareFunction",
    "src/routes/Route.js~Route.ParamMiddlewareFunction",
    "typedef"
  ],
  [
    "src/routes/route.js~route.params",
    "typedef/index.html#static-typedef-Params",
    "src/routes/Route.js~Route.Params",
    "typedef"
  ],
  [
    "src/routes/route.js~route.patch",
    "class/src/routes/Route.js~Route.html#static-member-Patch",
    "src/routes/Route.js~Route.Patch",
    "member"
  ],
  [
    "src/routes/route.js~route.post",
    "class/src/routes/Route.js~Route.html#static-member-Post",
    "src/routes/Route.js~Route.Post",
    "member"
  ],
  [
    "src/routes/route.js~route.postparamsfilter",
    "typedef/index.html#static-typedef-PostParamsFilter",
    "src/routes/Route.js~Route.PostParamsFilter",
    "typedef"
  ],
  [
    "src/routes/route.js~route.put",
    "class/src/routes/Route.js~Route.html#static-member-Put",
    "src/routes/Route.js~Route.Put",
    "member"
  ],
  [
    "src/routes/route.js~route.route",
    "class/src/routes/Route.js~Route.html#static-member-Route",
    "src/routes/Route.js~Route.Route",
    "member"
  ],
  [
    "src/routes/route.js~route.routeparams",
    "typedef/index.html#static-typedef-RouteParams",
    "src/routes/Route.js~Route.RouteParams",
    "typedef"
  ],
  [
    "src/routes/route.js~route.statuscode",
    "class/src/routes/Route.js~Route.html#static-member-StatusCode",
    "src/routes/Route.js~Route.StatusCode",
    "member"
  ],
  [
    "src/routes/route.js~route.displaylog",
    "class/src/routes/Route.js~Route.html#static-member-displayLog",
    "src/routes/Route.js~Route.displayLog",
    "member"
  ],
  [
    "src/utils/errorapp.js",
    "file/src/utils/ErrorApp.js.html",
    "src/utils/ErrorApp.js",
    "file"
  ],
  [
    "src/utils/errorapp.js~errorapp#constructor",
    "class/src/utils/ErrorApp.js~ErrorApp.html#instance-constructor-constructor",
    "src/utils/ErrorApp.js~ErrorApp#constructor",
    "method"
  ],
  [
    "src/utils/errorapp.js~errorapp#message",
    "class/src/utils/ErrorApp.js~ErrorApp.html#instance-member-message",
    "src/utils/ErrorApp.js~ErrorApp#message",
    "member"
  ],
  [
    "src/utils/errorapp.js~errorapp#status",
    "class/src/utils/ErrorApp.js~ErrorApp.html#instance-member-status",
    "src/utils/ErrorApp.js~ErrorApp#status",
    "member"
  ],
  [
    "src/utils/errorapp.js~errorapp#totranslate",
    "class/src/utils/ErrorApp.js~ErrorApp.html#instance-member-toTranslate",
    "src/utils/ErrorApp.js~ErrorApp#toTranslate",
    "member"
  ]
]