window.esdocSearchIndex = [
  [
    "koa-smart/src/app.js~app",
    "class/src/App.js~App.html",
    "<span>App</span> <span class=\"search-result-import-path\">koa-smart/src/App.js</span>",
    "class"
  ],
  [
    "koa-smart/src/utils/errorapp.js~errorapp",
    "class/src/utils/ErrorApp.js~ErrorApp.html",
    "<span>ErrorApp</span> <span class=\"search-result-import-path\">koa-smart/src/utils/ErrorApp.js</span>",
    "class"
  ],
  [
    "koa-smart/src/routes/route.js~route",
    "class/src/routes/Route.js~Route.html",
    "<span>Route</span> <span class=\"search-result-import-path\">koa-smart/src/routes/Route.js</span>",
    "class"
  ],
  [
    "koa-smart/src/routes/routedecorators.js~routedecorators",
    "class/src/routes/RouteDecorators.js~RouteDecorators.html",
    "<span>RouteDecorators</span> <span class=\"search-result-import-path\">koa-smart/src/routes/RouteDecorators.js</span>",
    "class"
  ],
  [
    "koa-smart/src/middlewares/adddefaultbody.js~adddefaultbody",
    "function/index.html#static-function-addDefaultBody",
    "<span>addDefaultBody</span> <span class=\"search-result-import-path\">koa-smart/src/middlewares/addDefaultBody.js</span>",
    "function"
  ],
  [
    "koa-smart/src/utils/utils.js~capitalize",
    "function/index.html#static-function-capitalize",
    "<span>capitalize</span> <span class=\"search-result-import-path\">koa-smart/src/utils/utils.js</span>",
    "function"
  ],
  [
    "koa-smart/src/utils/utils.js~dateyyyymmdd",
    "function/index.html#static-function-dateYYYYMMDD",
    "<span>dateYYYYMMDD</span> <span class=\"search-result-import-path\">koa-smart/src/utils/utils.js</span>",
    "function"
  ],
  [
    "koa-smart/src/utils/utils.js~deepcopy",
    "function/index.html#static-function-deepCopy",
    "<span>deepCopy</span> <span class=\"search-result-import-path\">koa-smart/src/utils/utils.js</span>",
    "function"
  ],
  [
    "koa-smart/src/middlewares/handleerror.js~handleerror",
    "function/index.html#static-function-handleError",
    "<span>handleError</span> <span class=\"search-result-import-path\">koa-smart/src/middlewares/handleError.js</span>",
    "function"
  ],
  [
    "koa-smart/src/utils/utils.js~isarray",
    "function/index.html#static-function-isArray",
    "<span>isArray</span> <span class=\"search-result-import-path\">koa-smart/src/utils/utils.js</span>",
    "function"
  ],
  [
    "koa-smart/src/utils/utils.param.js~isdatebetween",
    "function/index.html#static-function-isDateBetween",
    "<span>isDateBetween</span> <span class=\"search-result-import-path\">koa-smart/src/utils/utils.param.js</span>",
    "function"
  ],
  [
    "koa-smart/src/utils/utils.js~isempty",
    "function/index.html#static-function-isEmpty",
    "<span>isEmpty</span> <span class=\"search-result-import-path\">koa-smart/src/utils/utils.js</span>",
    "function"
  ],
  [
    "koa-smart/src/utils/utils.js~isobject",
    "function/index.html#static-function-isObject",
    "<span>isObject</span> <span class=\"search-result-import-path\">koa-smart/src/utils/utils.js</span>",
    "function"
  ],
  [
    "koa-smart/src/utils/utils.js~jsondecode",
    "function/index.html#static-function-jsonDecode",
    "<span>jsonDecode</span> <span class=\"search-result-import-path\">koa-smart/src/utils/utils.js</span>",
    "function"
  ],
  [
    "koa-smart/src/utils/utils.js~jsonencode",
    "function/index.html#static-function-jsonEncode",
    "<span>jsonEncode</span> <span class=\"search-result-import-path\">koa-smart/src/utils/utils.js</span>",
    "function"
  ],
  [
    "koa-smart/src/utils/utils.js~lodash",
    "variable/index.html#static-variable-lodash",
    "<span>lodash</span> <span class=\"search-result-import-path\">koa-smart/src/utils/utils.js</span>",
    "variable"
  ],
  [
    "koa-smart/src/middlewares/logger.js~logger",
    "function/index.html#static-function-logger",
    "<span>logger</span> <span class=\"search-result-import-path\">koa-smart/src/middlewares/logger.js</span>",
    "function"
  ],
  [
    "koa-smart/src/utils/utils.js~notempty",
    "function/index.html#static-function-notEmpty",
    "<span>notEmpty</span> <span class=\"search-result-import-path\">koa-smart/src/utils/utils.js</span>",
    "function"
  ],
  [
    "koa-smart/src/middlewares/notfound.js~notfound",
    "function/index.html#static-function-notFound",
    "<span>notFound</span> <span class=\"search-result-import-path\">koa-smart/src/middlewares/notFound.js</span>",
    "function"
  ],
  [
    "koa-smart/src/utils/utils.js~nullifempty",
    "function/index.html#static-function-nullIfEmpty",
    "<span>nullIfEmpty</span> <span class=\"search-result-import-path\">koa-smart/src/utils/utils.js</span>",
    "function"
  ],
  [
    "koa-smart/src/utils/utils.js~objvaltoarray",
    "function/index.html#static-function-objValToArray",
    "<span>objValToArray</span> <span class=\"search-result-import-path\">koa-smart/src/utils/utils.js</span>",
    "function"
  ],
  [
    "koa-smart/src/utils/utils.js~random",
    "function/index.html#static-function-random",
    "<span>random</span> <span class=\"search-result-import-path\">koa-smart/src/utils/utils.js</span>",
    "function"
  ],
  [
    "koa-smart/src/utils/utils.param.js~regex",
    "function/index.html#static-function-regex",
    "<span>regex</span> <span class=\"search-result-import-path\">koa-smart/src/utils/utils.param.js</span>",
    "function"
  ],
  [
    "koa-smart/src/utils/utils.param.js~test",
    "function/index.html#static-function-test",
    "<span>test</span> <span class=\"search-result-import-path\">koa-smart/src/utils/utils.param.js</span>",
    "function"
  ],
  [
    "koa-smart/src/utils/utils.js~timeout",
    "function/index.html#static-function-timeout",
    "<span>timeout</span> <span class=\"search-result-import-path\">koa-smart/src/utils/utils.js</span>",
    "function"
  ],
  [
    "koa-smart/src/utils/utils.js~tolowercase",
    "function/index.html#static-function-toLowerCase",
    "<span>toLowerCase</span> <span class=\"search-result-import-path\">koa-smart/src/utils/utils.js</span>",
    "function"
  ],
  [
    "koa-smart/src/utils/utils.js~tonumber",
    "function/index.html#static-function-toNumber",
    "<span>toNumber</span> <span class=\"search-result-import-path\">koa-smart/src/utils/utils.js</span>",
    "function"
  ],
  [
    "koa-smart/src/utils/utils.param.js~trasform",
    "function/index.html#static-function-trasform",
    "<span>trasform</span> <span class=\"search-result-import-path\">koa-smart/src/utils/utils.param.js</span>",
    "function"
  ],
  [
    "koa-smart/src/utils/utils.js~trim",
    "function/index.html#static-function-trim",
    "<span>trim</span> <span class=\"search-result-import-path\">koa-smart/src/utils/utils.js</span>",
    "function"
  ],
  [
    "koa-smart/src/utils/utils.js~ucfirst",
    "function/index.html#static-function-ucFirst",
    "<span>ucFirst</span> <span class=\"search-result-import-path\">koa-smart/src/utils/utils.js</span>",
    "function"
  ],
  [
    "koa-smart/src/utils/utils.js~wait",
    "variable/index.html#static-variable-wait",
    "<span>wait</span> <span class=\"search-result-import-path\">koa-smart/src/utils/utils.js</span>",
    "variable"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/app.js",
    "file/src/App.js.html",
    "src/App.js",
    "file"
  ],
  [
    "src/app.js~app#_getallroutes",
    "class/src/App.js~App.html#instance-method-_getAllRoutes",
    "src/App.js~App#_getAllRoutes",
    "method"
  ],
  [
    "src/app.js~app#addmiddleware",
    "class/src/App.js~App.html#instance-method-addMiddleware",
    "src/App.js~App#addMiddleware",
    "method"
  ],
  [
    "src/app.js~app#addmiddlewares",
    "class/src/App.js~App.html#instance-method-addMiddlewares",
    "src/App.js~App#addMiddlewares",
    "method"
  ],
  [
    "src/app.js~app#app",
    "class/src/App.js~App.html#instance-member-app",
    "src/App.js~App#app",
    "member"
  ],
  [
    "src/app.js~app#constructor",
    "class/src/App.js~App.html#instance-constructor-constructor",
    "src/App.js~App#constructor",
    "method"
  ],
  [
    "src/app.js~app#mountfolder",
    "class/src/App.js~App.html#instance-method-mountFolder",
    "src/App.js~App#mountFolder",
    "method"
  ],
  [
    "src/app.js~app#port",
    "class/src/App.js~App.html#instance-member-port",
    "src/App.js~App#port",
    "member"
  ],
  [
    "src/app.js~app#routeparam",
    "class/src/App.js~App.html#instance-member-routeParam",
    "src/App.js~App#routeParam",
    "member"
  ],
  [
    "src/app.js~app#routes",
    "class/src/App.js~App.html#instance-member-routes",
    "src/App.js~App#routes",
    "member"
  ],
  [
    "src/app.js~app#start",
    "class/src/App.js~App.html#instance-method-start",
    "src/App.js~App#start",
    "method"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/middlewares/adddefaultbody.js",
    "file/src/middlewares/addDefaultBody.js.html",
    "src/middlewares/addDefaultBody.js",
    "file"
  ],
  [
    "src/middlewares/handleerror.js",
    "file/src/middlewares/handleError.js.html",
    "src/middlewares/handleError.js",
    "file"
  ],
  [
    "src/middlewares/handleerror.js~optionerrors",
    "typedef/index.html#static-typedef-OptionErrors",
    "src/middlewares/handleError.js~OptionErrors",
    "typedef"
  ],
  [
    "src/middlewares/index.js",
    "file/src/middlewares/index.js.html",
    "src/middlewares/index.js",
    "file"
  ],
  [
    "src/middlewares/logger.js",
    "file/src/middlewares/logger.js.html",
    "src/middlewares/logger.js",
    "file"
  ],
  [
    "src/middlewares/notfound.js",
    "file/src/middlewares/notFound.js.html",
    "src/middlewares/notFound.js",
    "file"
  ],
  [
    "src/routes/route.js",
    "file/src/routes/Route.js.html",
    "src/routes/Route.js",
    "file"
  ],
  [
    "src/routes/route.js~koa",
    "http://koajs.com/#application",
    "src/routes/Route.js~Koa",
    "external"
  ],
  [
    "src/routes/route.js~koacontext",
    "http://koajs.com/#api",
    "src/routes/Route.js~KoaContext",
    "external"
  ],
  [
    "src/routes/route.js~route#_beforeroute",
    "class/src/routes/Route.js~Route.html#instance-method-_beforeRoute",
    "src/routes/Route.js~Route#_beforeRoute",
    "method"
  ],
  [
    "src/routes/route.js~route#_mlparams",
    "class/src/routes/Route.js~Route.html#instance-method-_mlParams",
    "src/routes/Route.js~Route#_mlParams",
    "method"
  ],
  [
    "src/routes/route.js~route#_mlparamsexecfunc",
    "class/src/routes/Route.js~Route.html#instance-method-_mlParamsExecFunc",
    "src/routes/Route.js~Route#_mlParamsExecFunc",
    "method"
  ],
  [
    "src/routes/route.js~route#_mltestparams",
    "class/src/routes/Route.js~Route.html#instance-method-_mlTestParams",
    "src/routes/Route.js~Route#_mlTestParams",
    "method"
  ],
  [
    "src/routes/route.js~route#_paramshassubelement",
    "class/src/routes/Route.js~Route.html#instance-method-_paramsHasSubElement",
    "src/routes/Route.js~Route#_paramsHasSubElement",
    "method"
  ],
  [
    "src/routes/route.js~route#_paramsnormalize",
    "class/src/routes/Route.js~Route.html#instance-method-_paramsNormalize",
    "src/routes/Route.js~Route#_paramsNormalize",
    "method"
  ],
  [
    "src/routes/route.js~route#_use",
    "class/src/routes/Route.js~Route.html#instance-method-_use",
    "src/routes/Route.js~Route#_use",
    "method"
  ],
  [
    "src/routes/route.js~route#addratelimit",
    "class/src/routes/Route.js~Route.html#instance-method-addRateLimit",
    "src/routes/Route.js~Route#addRateLimit",
    "method"
  ],
  [
    "src/routes/route.js~route#allroutesinstance",
    "class/src/routes/Route.js~Route.html#instance-member-allRoutesInstance",
    "src/routes/Route.js~Route#allRoutesInstance",
    "member"
  ],
  [
    "src/routes/route.js~route#app",
    "class/src/routes/Route.js~Route.html#instance-member-app",
    "src/routes/Route.js~Route#app",
    "member"
  ],
  [
    "src/routes/route.js~route#assert",
    "class/src/routes/Route.js~Route.html#instance-method-assert",
    "src/routes/Route.js~Route#assert",
    "method"
  ],
  [
    "src/routes/route.js~route#beforeroute",
    "class/src/routes/Route.js~Route.html#instance-method-beforeRoute",
    "src/routes/Route.js~Route#beforeRoute",
    "method"
  ],
  [
    "src/routes/route.js~route#body",
    "class/src/routes/Route.js~Route.html#instance-method-body",
    "src/routes/Route.js~Route#body",
    "method"
  ],
  [
    "src/routes/route.js~route#bodyget",
    "class/src/routes/Route.js~Route.html#instance-method-bodyGet",
    "src/routes/Route.js~Route#bodyGet",
    "method"
  ],
  [
    "src/routes/route.js~route#constructor",
    "class/src/routes/Route.js~Route.html#instance-constructor-constructor",
    "src/routes/Route.js~Route#constructor",
    "method"
  ],
  [
    "src/routes/route.js~route#disable",
    "class/src/routes/Route.js~Route.html#instance-member-disable",
    "src/routes/Route.js~Route#disable",
    "member"
  ],
  [
    "src/routes/route.js~route#getratelimit",
    "class/src/routes/Route.js~Route.html#instance-method-getRateLimit",
    "src/routes/Route.js~Route#getRateLimit",
    "method"
  ],
  [
    "src/routes/route.js~route#koarouter",
    "class/src/routes/Route.js~Route.html#instance-member-koaRouter",
    "src/routes/Route.js~Route#koaRouter",
    "member"
  ],
  [
    "src/routes/route.js~route#log",
    "class/src/routes/Route.js~Route.html#instance-method-log",
    "src/routes/Route.js~Route#log",
    "method"
  ],
  [
    "src/routes/route.js~route#middlewares",
    "class/src/routes/Route.js~Route.html#instance-member-middlewares",
    "src/routes/Route.js~Route#middlewares",
    "member"
  ],
  [
    "src/routes/route.js~route#model",
    "class/src/routes/Route.js~Route.html#instance-member-model",
    "src/routes/Route.js~Route#model",
    "member"
  ],
  [
    "src/routes/route.js~route#models",
    "class/src/routes/Route.js~Route.html#instance-member-models",
    "src/routes/Route.js~Route#models",
    "member"
  ],
  [
    "src/routes/route.js~route#mount",
    "class/src/routes/Route.js~Route.html#instance-method-mount",
    "src/routes/Route.js~Route#mount",
    "method"
  ],
  [
    "src/routes/route.js~route#paramsget",
    "class/src/routes/Route.js~Route.html#instance-method-paramsGet",
    "src/routes/Route.js~Route#paramsGet",
    "method"
  ],
  [
    "src/routes/route.js~route#prefix",
    "class/src/routes/Route.js~Route.html#instance-member-prefix",
    "src/routes/Route.js~Route#prefix",
    "member"
  ],
  [
    "src/routes/route.js~route#privatekeyinparamsroute",
    "class/src/routes/Route.js~Route.html#instance-member-privateKeyInParamsRoute",
    "src/routes/Route.js~Route#privateKeyInParamsRoute",
    "member"
  ],
  [
    "src/routes/route.js~route#send",
    "class/src/routes/Route.js~Route.html#instance-method-send",
    "src/routes/Route.js~Route#send",
    "method"
  ],
  [
    "src/routes/route.js~route#sendbadrequest",
    "class/src/routes/Route.js~Route.html#instance-method-sendBadRequest",
    "src/routes/Route.js~Route#sendBadRequest",
    "method"
  ],
  [
    "src/routes/route.js~route#sendcreated",
    "class/src/routes/Route.js~Route.html#instance-method-sendCreated",
    "src/routes/Route.js~Route#sendCreated",
    "method"
  ],
  [
    "src/routes/route.js~route#sendforbidden",
    "class/src/routes/Route.js~Route.html#instance-method-sendForbidden",
    "src/routes/Route.js~Route#sendForbidden",
    "method"
  ],
  [
    "src/routes/route.js~route#sendinternalservererror",
    "class/src/routes/Route.js~Route.html#instance-method-sendInternalServerError",
    "src/routes/Route.js~Route#sendInternalServerError",
    "method"
  ],
  [
    "src/routes/route.js~route#sendnocontent",
    "class/src/routes/Route.js~Route.html#instance-method-sendNoContent",
    "src/routes/Route.js~Route#sendNoContent",
    "method"
  ],
  [
    "src/routes/route.js~route#sendnotfound",
    "class/src/routes/Route.js~Route.html#instance-method-sendNotFound",
    "src/routes/Route.js~Route#sendNotFound",
    "method"
  ],
  [
    "src/routes/route.js~route#sendok",
    "class/src/routes/Route.js~Route.html#instance-method-sendOk",
    "src/routes/Route.js~Route#sendOk",
    "method"
  ],
  [
    "src/routes/route.js~route#sendunauthorized",
    "class/src/routes/Route.js~Route.html#instance-method-sendUnauthorized",
    "src/routes/Route.js~Route#sendUnauthorized",
    "method"
  ],
  [
    "src/routes/route.js~route#throw",
    "class/src/routes/Route.js~Route.html#instance-method-throw",
    "src/routes/Route.js~Route#throw",
    "method"
  ],
  [
    "src/routes/route.js~route.delete",
    "class/src/routes/Route.js~Route.html#static-member-Delete",
    "src/routes/Route.js~Route.Delete",
    "member"
  ],
  [
    "src/routes/route.js~route.get",
    "class/src/routes/Route.js~Route.html#static-member-Get",
    "src/routes/Route.js~Route.Get",
    "member"
  ],
  [
    "src/routes/route.js~route.parammiddlewarefunction",
    "typedef/index.html#static-typedef-ParamMiddlewareFunction",
    "src/routes/Route.js~Route.ParamMiddlewareFunction",
    "typedef"
  ],
  [
    "src/routes/route.js~route.params",
    "typedef/index.html#static-typedef-Params",
    "src/routes/Route.js~Route.Params",
    "typedef"
  ],
  [
    "src/routes/route.js~route.patch",
    "class/src/routes/Route.js~Route.html#static-member-Patch",
    "src/routes/Route.js~Route.Patch",
    "member"
  ],
  [
    "src/routes/route.js~route.post",
    "class/src/routes/Route.js~Route.html#static-member-Post",
    "src/routes/Route.js~Route.Post",
    "member"
  ],
  [
    "src/routes/route.js~route.postparamsfilter",
    "typedef/index.html#static-typedef-PostParamsFilter",
    "src/routes/Route.js~Route.PostParamsFilter",
    "typedef"
  ],
  [
    "src/routes/route.js~route.put",
    "class/src/routes/Route.js~Route.html#static-member-Put",
    "src/routes/Route.js~Route.Put",
    "member"
  ],
  [
    "src/routes/route.js~route.route",
    "class/src/routes/Route.js~Route.html#static-member-Route",
    "src/routes/Route.js~Route.Route",
    "member"
  ],
  [
    "src/routes/route.js~route.routeparams",
    "typedef/index.html#static-typedef-RouteParams",
    "src/routes/Route.js~Route.RouteParams",
    "typedef"
  ],
  [
    "src/routes/route.js~route.statuscode",
    "class/src/routes/Route.js~Route.html#static-member-StatusCode",
    "src/routes/Route.js~Route.StatusCode",
    "member"
  ],
  [
    "src/routes/route.js~route.displaylog",
    "class/src/routes/Route.js~Route.html#static-member-displayLog",
    "src/routes/Route.js~Route.displayLog",
    "member"
  ],
  [
    "src/routes/routedecorators.js",
    "file/src/routes/RouteDecorators.js.html",
    "src/routes/RouteDecorators.js",
    "file"
  ],
  [
    "src/routes/routedecorators.js~routedecorators.delete",
    "class/src/routes/RouteDecorators.js~RouteDecorators.html#static-method-Delete",
    "src/routes/RouteDecorators.js~RouteDecorators.Delete",
    "method"
  ],
  [
    "src/routes/routedecorators.js~routedecorators.get",
    "class/src/routes/RouteDecorators.js~RouteDecorators.html#static-method-Get",
    "src/routes/RouteDecorators.js~RouteDecorators.Get",
    "method"
  ],
  [
    "src/routes/routedecorators.js~routedecorators.patch",
    "class/src/routes/RouteDecorators.js~RouteDecorators.html#static-method-Patch",
    "src/routes/RouteDecorators.js~RouteDecorators.Patch",
    "method"
  ],
  [
    "src/routes/routedecorators.js~routedecorators.post",
    "class/src/routes/RouteDecorators.js~RouteDecorators.html#static-method-Post",
    "src/routes/RouteDecorators.js~RouteDecorators.Post",
    "method"
  ],
  [
    "src/routes/routedecorators.js~routedecorators.put",
    "class/src/routes/RouteDecorators.js~RouteDecorators.html#static-method-Put",
    "src/routes/RouteDecorators.js~RouteDecorators.Put",
    "method"
  ],
  [
    "src/routes/routedecorators.js~routedecorators.route",
    "class/src/routes/RouteDecorators.js~RouteDecorators.html#static-method-Route",
    "src/routes/RouteDecorators.js~RouteDecorators.Route",
    "method"
  ],
  [
    "src/routes/routedecorators.js~routedecorators._addroute",
    "class/src/routes/RouteDecorators.js~RouteDecorators.html#static-method-_addRoute",
    "src/routes/RouteDecorators.js~RouteDecorators._addRoute",
    "method"
  ],
  [
    "src/routes/routedecorators.js~routedecorators._getroutefrommethode",
    "class/src/routes/RouteDecorators.js~RouteDecorators.html#static-method-_getRouteFromMethode",
    "src/routes/RouteDecorators.js~RouteDecorators._getRouteFromMethode",
    "method"
  ],
  [
    "src/routes/routedecorators.js~routedecorators._initdata",
    "class/src/routes/RouteDecorators.js~RouteDecorators.html#static-method-_initData",
    "src/routes/RouteDecorators.js~RouteDecorators._initData",
    "method"
  ],
  [
    "src/utils/errorapp.js",
    "file/src/utils/ErrorApp.js.html",
    "src/utils/ErrorApp.js",
    "file"
  ],
  [
    "src/utils/errorapp.js~errorapp#constructor",
    "class/src/utils/ErrorApp.js~ErrorApp.html#instance-constructor-constructor",
    "src/utils/ErrorApp.js~ErrorApp#constructor",
    "method"
  ],
  [
    "src/utils/errorapp.js~errorapp#message",
    "class/src/utils/ErrorApp.js~ErrorApp.html#instance-member-message",
    "src/utils/ErrorApp.js~ErrorApp#message",
    "member"
  ],
  [
    "src/utils/errorapp.js~errorapp#status",
    "class/src/utils/ErrorApp.js~ErrorApp.html#instance-member-status",
    "src/utils/ErrorApp.js~ErrorApp#status",
    "member"
  ],
  [
    "src/utils/errorapp.js~errorapp#totranslate",
    "class/src/utils/ErrorApp.js~ErrorApp.html#instance-member-toTranslate",
    "src/utils/ErrorApp.js~ErrorApp#toTranslate",
    "member"
  ],
  [
    "src/utils/statuscode.js",
    "file/src/utils/StatusCode.js.html",
    "src/utils/StatusCode.js",
    "file"
  ],
  [
    "src/utils/index.js",
    "file/src/utils/index.js.html",
    "src/utils/index.js",
    "file"
  ],
  [
    "src/utils/utils.js",
    "file/src/utils/utils.js.html",
    "src/utils/utils.js",
    "file"
  ],
  [
    "src/utils/utils.param.js",
    "file/src/utils/utils.param.js.html",
    "src/utils/utils.param.js",
    "file"
  ]
]